name: Push and update Salt

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [lothlorien, rivendell]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Update Salt
        run: |
          rm -rf .git*

          if [ ! -d /srv/salt ]; then
              mkdir /srv/salt
          fi
          cp -r ./ /srv/salt
